"""Add marks column, remove gpa

Revision ID: 9c684101241a
Revises: 3b5fa40dd45d
Create Date: 2025-05-20 10:28:33.604085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c684101241a'
down_revision: Union[str, None] = '3b5fa40dd45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('marks', sa.Float(), nullable=True))
    op.drop_column('students', 'gpa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gpa', sa.FLOAT(), nullable=True))
    op.drop_column('students', 'marks')
    # ### end Alembic commands ###
